### PR TITLE
Update Manager.php

### PR DESCRIPTION
**Pull request by joao-gsneto**
Adding missing third parameter on str_replace function on setEntityUrl method.

### CODE REVIEW

**Comment by joelibaceta** [comment]
@mminestrelli could you check this? if you agree I suggest a merge

**Comment by fgilio** [comment]
Can we all agree this is a no brainer https://php.net/manual/en/function.str-replace.php ?

**Comment by santiagoguinle** [comment]
+1

**Comment by phgoncalves** [comment]
Thanks for your contributtion, @joao-gsneto!
This issue was fixed in the version 1.3.1.

**Pull request closed without merging**
